package dev.zalaya.jade.infrastructure.persistence.repository;

import dev.zalaya.jade.infrastructure.persistence.entity.ProjectEntity;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.function.Executable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.dao.DataIntegrityViolationException;

import static dev.zalaya.jade.infrastructure.persistence.entity.ProjectEntityFixture.*;

import static org.assertj.core.api.Assertions.*;

@DataJpaTest
class ProjectJpaRepositoryTest {

    @Autowired
    private ProjectJpaRepository repository;

    @Test
    void givenNewProject_whenSave_thenAutogeneratedFieldsAreGenerated() {
        // Given
        ProjectEntity project = aProjectEntityWithDefaultNameAndPath();

        // When
        ProjectEntity persistedProject = repository.saveAndFlush(project);

        // Then
        assertThat(persistedProject.getId()).isNotNull();
        assertThat(persistedProject.getCreatedAt()).isNotNull();
        assertThat(persistedProject.getUpdatedAt()).isNull();
    }

    @Test
    void givenNewProjectWithoutName_whenSave_thenThrowsDataIntegrityViolationException() {
        // Given
        ProjectEntity project = aProjectEntityWithDefaultPathWithName(null);

        // When
        Executable executable = () -> repository.saveAndFlush(project);

        // Then
        assertThatThrownBy(executable::execute).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void givenNewProjectWithoutPath_whenSave_thenThrowsDataIntegrityViolationException() {
        // Given
        ProjectEntity project = aProjectEntityWithDefaultNameWithPath(null);

        // When
        Executable executable = () -> repository.saveAndFlush(project);

        // Then
        assertThatThrownBy(executable::execute).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void givenPersistedProject_whenSave_thenUpdateAtIsUpdated() {
        // Given
        ProjectEntity project = aProjectEntityWithDefaultNameAndPath();
        ProjectEntity persistedProject = repository.saveAndFlush(project);
        persistedProject.setName("Updated Project");
        persistedProject.setPath("/updated-project");

        // When
        ProjectEntity updatedProject = repository.saveAndFlush(persistedProject);

        // Then
        assertThat(updatedProject.getCreatedAt()).isEqualTo(persistedProject.getCreatedAt());
        assertThat(updatedProject.getUpdatedAt()).isNotNull().isAfterOrEqualTo(persistedProject.getUpdatedAt());
    }

}
